### ISSUE TITLE
Bad results from filter after time stamp jump

### ISSUE THREAD

**Issue by nachumlerner** [CCNYRoboticsLab/imu_tools#160]
Hi
Our robot doesn't have a permanent internet connection so when it is turned on its clock starts from. 1.1.2016. After startup our robot starts calculating orientation by using madgwick filter. After a few minutes we get wifi signal and the clock adjusts to correct time. When the clock adjusts we get a big jump in orientation from the filter even if the robot is stationary on the floor.
This jump doesn't change and the robot will continue thinking it is at 180 deg
If we restart the filter we will get the correct orientation (can be seen in image in /sensors/imu_filtered1).
Any advice?
Thanks
![Screenshot from 2022-05-15 12-41-27](https://user-images.githubusercontent.com/84379955/168466582-bf6d4548-1a8c-4eb2-80c5-a2f7549ecefa.png)

**Comment by mintar** [comment]
>  Any advice?

Just avoid these clock jumps. :)

Sorry to not be more helpful, but you're feeding false information into the filter. The IMU data that goes into the filter says that there is a time gap of 6 years in the sensor data, and the filter does the best it can based on that information - garbage in, garbage out. It doesn't seem that this should be handled in the madgwick filter, but in the data that goes into it.

**Comment by nachumlerner** [comment]
Is there a way to initialize the yaw angle after relaunch so it will be continuous with the angle before the jump?

**Comment by mintar** [comment]
There's the parameter `yaw_offset` that you could probably abuse for this purpose. However, I'm afraid you'll get plenty of other errors in other ROS nodes that are caused by the time jump, such as TF buffers being invalidated and so on. Can't you add a Real-Time Clock to your robot so that you can fix the root of all problems, instead of adding tons of workarounds all over the place?

**Comment by nachumlerner** [comment]
Unfortunately we can't add anything to the robot, thanks for the advice

**Comment by mintar** [comment]
That's a bummer. I dug a bit deeper, and it turns out that you can fix your problem with `imu_filter_madgwick` by setting the parameter `constant_dt` to the rate at which your IMU publishes. If that parameter is set, `imu_filter_madgwick` will no longer look at the time stamp of the messages, but uses the given $\Delta t$ in its calculations.
