### ISSUE TITLE
Unable to set ~publish_debug_topics to True for imu_complementary_filter

### ISSUE THREAD

**Issue by DylanRobertBennett** [CCNYRoboticsLab/imu_tools#180]
I would like to see the 'imu/rpy/filtered' topic for roll, pitch, and yaw angles published by the imu_complementary_filter.

I am publishing 'imu/data_raw' from another node so the imu_complementary_filter should be picking that up with its subscriber.

Here are the commands I used to launch the imu_complementary_filter, neither of which published the 'imu/rpy/filtered' topic:

ros2 launch imu_complementary_filter complementary_filter.launch.py ~publish_debug_topics:=true
ros2 launch imu_complementary_filter complementary_filter.launch.py publish_debug_topics:=true

I do see 'imu/data' but that isn't what Im looking for.

Is this a bug or am I going about this wrong?

Thank you

**Comment by mintar** [comment]
The launch file doesn't have a *launch argument* called `publish_debug_topics`, so that's why nothing is happening. The node does have a *parameter* `publish_debug_topics`. So either you edit the launch file to add a launch argument that passes on its value to the node parameter, or you set the parameter directly like the other parameters (`do_bias_estimation` etc.).
