### ISSUE TITLE
rpy/raw debug topic not published when use_mag is True

### ISSUE THREAD

**Issue by CatherineH** [CCNYRoboticsLab/imu_tools#44]
I have the following in my launch file:

```
  <node pkg="imu_filter_madgwick" type="imu_filter_node" name="imu_filter_madgwick" output="screen" respawn="false" >
      <param name="~publish_debug_topics" value="True" />
      <param name="~use_mag" value="True" />
      <remap from="imu/data" to="imu/data2" />
  </node>
```

When use_mag is set to False, this generates the two topics /imu/rpy/raw and /imu/rpy/filtered. When use_mag is set to True, this only generates /imu/rpy/filtered. 

Is this the intended behaviour?

**Comment by mintar** [comment]
I could not reproduce the behavior you describe. Perhaps you had the param `publish_debug_topics` set to `false`, and another node was subscribing or publishing to `/imu/rpy/filtered`, so that's why this topic was there and the other not.

Could you try this to confirm?
- copy _only_ the snippet you posted into a separate launch file, surround it with `<launch>...</launch>`
- kill all roscores, roslaunch etc.; this is important to make sure that there are no cached parameters from previous launches
- now confirm that changing `use_mag` to `true`/`false` and launching the file doesn't affect the debug topics
